### PR TITLE
nc2tif v2

### PR DESCRIPTION
**Pull request by mastefan**
No errors, warnings or notes in RStudio...

Here's hoping that this one works!

### CODE REVIEW

**Comment by mastefan** [comment]
T-CI test failed. Leaving here to check on reasons for failure tomorrow.

**Comment by khufkens** [comment]
Hi Mike,

The build sometimes fails as the test routines are rather slow (depending on the load of Travis CI this happens). Look at the details (if these are public, they should list a timeout). In general if local checks are fine this should be ok, but I try to keep the build status OK (= public).

Thanks for catching the brick error on the one layer raster data for the annual data. 

I had a look at your code and noticed some redundancy. I think it would be better to kick out all files which exist in the system instead of doing this comparison in the for loop. This would cut the amount of code in half and reduce redundancy (repeats). 

Below some pseudo-ish code (did not check!) as an example:

```
tifs <- list.files(path=path, pattern="\\.tif$",  full.names = TRUE)
nc  <- list.files(path=path, pattern="\\.nc$", full.names = TRUE)
(or nc <- path.expand(file))

if (!overwrite){
nc_to_process <- nc[tools::file_path_sans_ext(nc) %in% tools::file_path_sans_ext(nc)]
} else  {
nc_to_process <- nc
}
```

You could list the files you skip but I wouldn't consider it highly valuable feedback. As this might take a long time depending on the amount of data adding a progress bar could be helpful.

```
  # implement a progress bar for graphical feedback
  # this to gauge speed limitations
  cat("This might take a while ... \n")
  pb = utils::txtProgressBar(min = 0, max = length(nc_to_process), style = 3)
 k = 1

for (i in nc_to_process){
     # progress bar for the models
     utils::setTxtProgressBar(pb, k);
     k = k + 1 # or if i is numeric (location) you can substitute i for k
     ...
}
```

### Other tips:

- You can abbreviate any() == FALSE as !any(), the reverse of the result (so if TRUE, make it FALSE). This makes the code a bit more concise.
- The file parameter is now a logical statement, which you mix later on if you do use it (becomes a path to a file). Mixing types like this is not ideal. I would use a default of NULL and check for its presence using is.null(file).

**Comment by khufkens** [comment]
Also you might have noticed that at a certain point if you check the package it will run tests. These tests are in the tests/testthat folder (only one test file there).

This allows you to do easy unit testing. So if you change a function, you can iterate through all the options and see if the function still works as desired. This is meant to trap bugs before they go public. I only started doing this recently and it has proven useful.

Ironically the function that wasn't in there nc2tif() did have a bug which I didn't catch and you did. So this is a virtual extra pair of eyes.

**Comment by khufkens** [comment]
In testthat, could you revert to the tempdir() notation. Writing in your current working directory pollutes the package and you might accidentally delete package files you need !

```
file.remove("tmin_1980_11207.nc",
             "tmin_1980_11207.tif",
             "tmin_1980_11207.tif.aux.xml")
```
you can do a 

```
file.remove(list.files(tempdir(),"tmin_*",full.names = TRUE))
```

While keeping things in tempdir()

More urgent is the added 3 to nc2tif, the true function is now nc2tif3 and nc2tif can thus not be found by testthat.

Addressing those everything should be set.

**Comment by mastefan** [comment]
Yes, I was just working on the testthat function. Sorry, I hadn't realized that my internal changes had pushed into this pull request.

I am just running another round of tests now - I wanted to look into the bug that you had flagged. Would you like a new pull request or will you be able to use this one with a new push?
Update - I see now that commits are visible here.

**Comment by khufkens** [comment]
As to the bug, you fixed this! I just referenced this for bookkeeping.

In the future if you want to add something it might be better to raise an issue, and then work on it. As such people could join the effort and can also follow who does what. Even between the two of us this is convenient so we don't work separately on the same issue.

**Comment by mastefan** [comment]
That makes sense, I will do so next time. Sorry if my trial and error on here has spammed your inbox! And thanks for your help along the way.

Looks like the T-CI check failed again. By my read this is happening in the testthat download and file conversion check because nc2tif is unable to open the downloaded file. The initial reason that I had changed the working directory in the testthat function on my end was because I was also having this issue. I found that setting a non-temporary directory resolved this. What are your thoughts here?

**Comment by khufkens** [comment]
No worries, thanks for the contributions.

nc2tif checks failed because the list.files() calls do not use full.names = TRUE so they only list the filenames not the full path.

**Pull request merged**
